version: '3.8'

services:
  monolith:
    build: monolith
    ports:
      - "8000:8000"
    volumes:
      - ./monolith:/app

  microservice:
    build: microservice
    ports:
      - "3000:3000"
    volumes:
      - ./microservice:/app

  oidc-provider:
    image: qlik/simple-oidc-provider
    environment:
      - CONFIG_FILE=/etc/config.json
      - USERS_FILE=/etc/users.json
    volumes:
      - ./reverse-proxy/oidc-config.json:/etc/config.json:ro
      - ./reverse-proxy/users.json:/etc/users.json:ro
    ports:
      - "9000:9000"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://172.17.0.1:9000
      - OAUTH2_PROXY_CLIENT_ID=oauth2-proxy
      - OAUTH2_PROXY_CLIENT_SECRET=secret
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:5000/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECRET=abcdefghiklmnlop
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_COOKIE_EXPIRE=168h0m0s
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_COOKIE_REFRESH=0
      - OAUTH2_PROXY_COOKIE_DOMAINS=localhost
      - OAUTH2_PROXY_WHITELIST_DOMAINS=localhost
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
    ports:
      - "4180:4180"
    depends_on:
      - oidc-provider

  reverse-proxy:
    build: reverse-proxy
    ports:
      - "5000:5000"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - oauth2-proxy